### ISSUE TITLE
Functional Fantasy

### ISSUE THREAD

**Issue by anastasia590** [ldtteam/stylecolonies#5]
Submission for the functional fantasy style 
yes it's complete, has all buildings including a quarry 
Yes I'm going to maintain it and don't mind pings in discord 
yes I have built it in survival 

Currently requires supplementaries and MrCrayfish furniture mod.  I will be removing supplementaries probably by this weekend  as it is in very few buildings after discovering problems in the survival test.   there are no problems with it currently but as I removed so much of it there is very little left and not worth keeping  because so few people will see this in their build tool.  All supplementaries is only decorative and will not have "missing blocks" apparent  candleholders, globe, clock - things like that nothing structural and nothing that is obviously missing.  
 working on a version 1.20+ that removes the furniture mod as well to make it easier for people to see in their build tool
  also planning more wall segments to go up and down hills, smaller corners and other gate options 
    Pros/cons features - Nested buildings  love them or hate them,  the only things that are NOT stand-alone is courier huts and a school, you have two school options one in the town library and one in the university but no stand alone.    Everything else that is nested is something you may want several of them so they all have stand alone 
    buildings don't all look the same so it's easier to tell them apart for managing your crafters etc. 
 no unobtainable blocks and no frog lights, blocks of netherite etc 
    musical decorations
     videos and more photos on [planet minecraft ](https://www.planetminecraft.com/account/manage/projects/6041583/)
![2023-09-27_17 42 23](https://github.com/ldtteam/stylecolonies/assets/121142637/215bd71f-4514-4400-9561-7386ba9ab9a5)
![2023-09-27_17 47 34](https://github.com/ldtteam/stylecolonies/assets/121142637/596bc8ef-f77f-4326-a938-891a7df9c745)

roads get holiday spirit at 3 & 4 and go back to colony banner at level 5 the powered rails WORK fine in survival and then players can ride too
![roads](https://github.com/ldtteam/stylecolonies/assets/121142637/d93c91bc-c07a-4613-b63e-3b946082a51e)

walls 
![wall](https://github.com/ldtteam/stylecolonies/assets/121142637/2a780055-dd81-46c4-a322-e4b729cd7ebe)

Mystical site (walls in background) 
![2023-08-20_10 21 14](https://github.com/ldtteam/stylecolonies/assets/121142637/58265a9a-7317-483f-9875-cd27acee1ab2)
forester hut 
![forester](https://github.com/ldtteam/stylecolonies/assets/121142637/f654f597-c074-4745-8ac8-50e849a02725)
 sawmil 
![sawmill](https://github.com/ldtteam/stylecolonies/assets/121142637/9a2450af-f9f2-4a2f-bdee-3ee953339a24)
 Farm 
![farm](https://github.com/ldtteam/stylecolonies/assets/121142637/cc29a965-6eca-4a32-9d43-86685b65c430)

![lavafarm](https://github.com/ldtteam/stylecolonies/assets/121142637/b9152d3e-4e90-487c-8c3b-1a6b0049109b)
![smeltery](https://github.com/ldtteam/stylecolonies/assets/121142637/a389c0df-cc33-4d29-8f69-ed039716fb69)
 Mine 
![mine](https://github.com/ldtteam/stylecolonies/assets/121142637/8c63a432-bf45-48ba-8a19-b5352b45ff9e)
 
![2023-09-26_12 00 17](https://github.com/ldtteam/stylecolonies/assets/121142637/e6f932fb-9b58-4b39-9e81-35a1cd6a93fa)
![2023-09-27_17 52 29](https://github.com/ldtteam/stylecolonies/assets/121142637/2750deea-4d5c-473b-b61a-872113d499fe)
![2023-09-27_17 18 46](https://github.com/ldtteam/stylecolonies/assets/121142637/7ba9fb3a-3295-486f-8cf8-050da492040f)
![2023-09-27_17 19 02](https://github.com/ldtteam/stylecolonies/assets/121142637/8e411aa3-1696-4fd7-b308-76441b446721)
![2023-09-27_17 19 24](https://github.com/ldtteam/stylecolonies/assets/121142637/fb8961b2-7613-4afd-b718-ae6bb3851326)
![2023-09-27_17 19 45](https://github.com/ldtteam/stylecolonies/assets/121142637/350a2246-3132-4dfb-bf82-1732a8155fd3)
![2023-09-27_17 20 06](https://github.com/ldtteam/stylecolonies/assets/121142637/18b11a3f-4906-42eb-961f-fe1ce91d15f1)
![2023-09-27_17 20 22](https://github.com/ldtteam/stylecolonies/assets/121142637/989478e8-b214-4b55-801e-f2efaf877008)
![2023-09-27_17 20 45](https://github.com/ldtteam/stylecolonies/assets/121142637/10b1daff-2b41-4e3e-983c-ac8d256ac300)

**Comment by Raycoms** [comment]
Sure thing! Do you know how to make a pull request or do you need our help with that?

**Comment by anastasia590** [comment]
I do not know how to make a pull request.  Sent from my iPhoneOn Oct 11, 2023, at 3:06 AM, Raycoms ***@***.***> wrote:﻿
Sure thing! Do you know how to make a pull request or do you need our help with that?

**Comment by Talyda** [comment]
Shouldn't we wait until the changes are made before doing any of that?
If you make the PR now, it will still need and use supplementaries.

**Comment by Thodor12** [comment]
At the time of the PR it can still be modified until it is merged, and even still afterwards too as long as it's not released yet

**Comment by Talyda** [comment]
Yeah, but the point of this is for us to judge whether it will be added to the mod. Shouldn't that wait until the style is ready?

**Comment by Thodor12** [comment]
The voting is done during time of the PR when it's indicated to be ready for a merge

**Comment by Talyda** [comment]
Right, and if they don't know how to do a PR wouldn't it be better to wait until it is ready? I mean, for their sake, so they don't have to worry about it more than once?
PR's are confusing if you don't know what you are doing. And editing one is even more so.
I guess, I just don't see the point in doing one now, when they already know it is going to change, and will be easier on them to not have to do it again right away
